CREATE DATABASE Gestion;
USE Gestion;
CREATE TABLE Clients
(
    id INT PRIMARY KEY NOT NULL,
    TYPE_DE_CLIENT VARCHAR(100),
    RAISON_SOCIALE VARCHAR(100),
    EMAIL VARCHAR(255),
    TELEPHONE VARCHAR(12),
    ADRESSE VARCHAR(255),
    CODE_POSTAL VARCHAR(5),
    VILLE VARCHAR(255)
)

CREATE TABLE IF NOT EXISTS Lignes (
    NOM_DU_PRODUIT TEXT,
    REFERENCE INTEGER,
    QUANTITE INTEGER,
    PRIX_UNITE INTEGER,
)

;
CREATE TABLE Factures
(
    N_FACTURE TEXT,
    CLIENT TEXT,
    DATE_EMISSION DATE,
    MONTANT_TOTAL INTEGER
)
;
SHOW DATABASES;
SHOW TABLES;